spring.application.name=backend-pos

jwt.secret=kTjZjv1vI7xPquyDYfq3KrJYl7vVCMDHg9o3AEp5FHB
jwt.expiration=3600000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
ssh.tunnel=false
step.default.cron=0 30 0 * * *

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema-pos
spring.datasource.username=postgres
spring.datasource.password=juanaraujo21
spring.datasource.driver-class-name=org.postgresql.Driver
