spring.application.name=backend-pos

# JWT
jwt.secret=kTjZjv1vI7xPquyDYfq3KrJYl7vVCMDHg9o3AEp5FHB
jwt.expiration=3600000

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema-pos
spring.datasource.username=postgres
spring.datasource.password=juanaraujo21
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OTROS
ssh.tunnel=false
step.default.cron=0 30 0 * * *